### ISSUE TITLE
Update the version of library dependencies

### ISSUE THREAD

**Issue by perfah** [perfah/wlroots-rs#1]
Such as:

- git submodule?
- Update bindgen to latest version
- Refactor deprecated function calls (such as 'bindgen::builder::whitelisted_type(...)')
- Remove references to protocols that no longer exists (such as 'wlroots/protocol/screenshooter.xml')

Make sure everything compiles.

**Comment by gynther-k** [comment]
Can I start with this issue?

**Comment by perfah** [comment]
@gynther-k Sure!

**Comment by perfah** [comment]
Looks like this was finalized with commit 7a97597
